### ISSUE TITLE
SUBMIT A POLL RESPONSE <User Story 2>

### ISSUE THREAD

**Issue by vladar21** [vladar21/Example-Agile-Project#4]
**User Story:** In order to **provide anonymous feedback** as a **User**, I can **choose to hide my identity ín the poll response**

## **Acceptance Criteria**:

**a.** The option should be provided as a checkbox
**b.** The checkbox should be “checked” by default
**c.** The option should appear next to the submit button
**d.** After submitting the default submission confirmation should be adjusted to include the user name.

## **Tasks**

- [x] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update the test scripts
- [ ] Test the functionality
